# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='emil',
            field=models.EmailField(default='1', max_length=32, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='1', max_length=32, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app01.Role', verbose_name='用户角色'),
        ),
    ]
